/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_simplecpp_Sender */

#ifndef _Included_examples_simplecpp_Sender
#define _Included_examples_simplecpp_Sender
#ifdef __cplusplus
extern "C" {
#endif
#undef examples_simplecpp_Sender_serialVersionUID
#define examples_simplecpp_Sender_serialVersionUID 3487495895819000LL
#undef examples_simplecpp_Sender_AP_MIN
#define examples_simplecpp_Sender_AP_MIN 0L
#undef examples_simplecpp_Sender_AP_INITIATED
#define examples_simplecpp_Sender_AP_INITIATED 1L
#undef examples_simplecpp_Sender_AP_ACTIVE
#define examples_simplecpp_Sender_AP_ACTIVE 2L
#undef examples_simplecpp_Sender_AP_IDLE
#define examples_simplecpp_Sender_AP_IDLE 3L
#undef examples_simplecpp_Sender_AP_SUSPENDED
#define examples_simplecpp_Sender_AP_SUSPENDED 4L
#undef examples_simplecpp_Sender_AP_WAITING
#define examples_simplecpp_Sender_AP_WAITING 5L
#undef examples_simplecpp_Sender_AP_DELETED
#define examples_simplecpp_Sender_AP_DELETED 6L
#undef examples_simplecpp_Sender_AP_MAX
#define examples_simplecpp_Sender_AP_MAX 13L
#undef examples_simplecpp_Sender_D_MIN
#define examples_simplecpp_Sender_D_MIN 9L
#undef examples_simplecpp_Sender_D_ACTIVE
#define examples_simplecpp_Sender_D_ACTIVE 10L
#undef examples_simplecpp_Sender_D_SUSPENDED
#define examples_simplecpp_Sender_D_SUSPENDED 20L
#undef examples_simplecpp_Sender_D_RETIRED
#define examples_simplecpp_Sender_D_RETIRED 30L
#undef examples_simplecpp_Sender_D_UNKNOWN
#define examples_simplecpp_Sender_D_UNKNOWN 40L
#undef examples_simplecpp_Sender_D_MAX
#define examples_simplecpp_Sender_D_MAX 41L
/*
 * Class:     examples_simplecpp_Sender
 * Method:    callNative
 * Signature: (Lmuscle/core/JNIConduitEntrance;)V
 */
JNIEXPORT void JNICALL Java_examples_simplecpp_Sender_callNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
