#ifndef MAIN_H
#define MAIN_H

#define MAIN_INTERNAL_ACCEPT 16
#define MAIN_READ_HELLO 17
#define MAIN_STUBBORN_TIMEOUT 18
#define MAIN_STUBBORN_CONNECT 19
#define MAIN_EXTERNAL_ACCEPT 20
#define MAIN_WRITE_HELLO 21

#endif // MAIN_H

