/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class muscle_Version */

#ifndef _Included_muscle_Version
#define _Included_muscle_Version
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     muscle_Version
 * Method:    nativeInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_muscle_Version_nativeInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
