/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_transmutable_Kernel */

#ifndef _Included_examples_transmutable_Kernel
#define _Included_examples_transmutable_Kernel
#ifdef __cplusplus
extern "C" {
#endif
#undef examples_transmutable_Kernel_serialVersionUID
#define examples_transmutable_Kernel_serialVersionUID 3487495895819000LL
#undef examples_transmutable_Kernel_AP_MIN
#define examples_transmutable_Kernel_AP_MIN 0L
#undef examples_transmutable_Kernel_AP_INITIATED
#define examples_transmutable_Kernel_AP_INITIATED 1L
#undef examples_transmutable_Kernel_AP_ACTIVE
#define examples_transmutable_Kernel_AP_ACTIVE 2L
#undef examples_transmutable_Kernel_AP_IDLE
#define examples_transmutable_Kernel_AP_IDLE 3L
#undef examples_transmutable_Kernel_AP_SUSPENDED
#define examples_transmutable_Kernel_AP_SUSPENDED 4L
#undef examples_transmutable_Kernel_AP_WAITING
#define examples_transmutable_Kernel_AP_WAITING 5L
#undef examples_transmutable_Kernel_AP_DELETED
#define examples_transmutable_Kernel_AP_DELETED 6L
#undef examples_transmutable_Kernel_AP_MAX
#define examples_transmutable_Kernel_AP_MAX 13L
#undef examples_transmutable_Kernel_D_MIN
#define examples_transmutable_Kernel_D_MIN 9L
#undef examples_transmutable_Kernel_D_ACTIVE
#define examples_transmutable_Kernel_D_ACTIVE 10L
#undef examples_transmutable_Kernel_D_SUSPENDED
#define examples_transmutable_Kernel_D_SUSPENDED 20L
#undef examples_transmutable_Kernel_D_RETIRED
#define examples_transmutable_Kernel_D_RETIRED 30L
#undef examples_transmutable_Kernel_D_UNKNOWN
#define examples_transmutable_Kernel_D_UNKNOWN 40L
#undef examples_transmutable_Kernel_D_MAX
#define examples_transmutable_Kernel_D_MAX 41L
/*
 * Class:     examples_transmutable_Kernel
 * Method:    callNative
 * Signature: (ILmuscle/core/JNIConduitExit;Lmuscle/core/JNIConduitEntrance;)V
 */
JNIEXPORT void JNICALL Java_examples_transmutable_Kernel_callNative
  (JNIEnv *, jobject, jint, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class examples_transmutable_Kernel_DA2S */

#ifndef _Included_examples_transmutable_Kernel_DA2S
#define _Included_examples_transmutable_Kernel_DA2S
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class examples_transmutable_Kernel_S2DA */

#ifndef _Included_examples_transmutable_Kernel_S2DA
#define _Included_examples_transmutable_Kernel_S2DA
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
